### ISSUE TITLE
Increase list of names

### ISSUE THREAD

**Issue by lonewarrior556** [bearjaws/docker-names#2]
Would it be possible to substantially increase the number of names here about 5x? So about 500 each? 
I could make a pr, are there any guidelines to follow?

**Comment by bearjaws** [comment]
This mirrors the list of docker names from https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go

If you want a name generator that has far more entropy, try https://github.com/bitpay/bitcore-mnemonic

Which generates names that contain 128bits of random data, which is the same size as a UUID / GUID.
